INSERT INTO TAB_USER(USR_ID, USR_USERNAME, USR_PASSWORD, USR_FIRST_NAME, USR_LAST_NAME) VALUES (1, 'admin', 'admin', 'The', 'Adminstrator');
INSERT INTO TAB_USER(USR_ID, USR_USERNAME, USR_PASSWORD, USR_FIRST_NAME, USR_LAST_NAME) VALUES (2, 'user', 'user', 'Dummy', 'User');

INSERT INTO TAB_ROLE(ROL_USR_ID, ROL_NAME) VALUES (1, 'ADMIN');
INSERT INTO TAB_ROLE(ROL_USR_ID, ROL_NAME) VALUES (1, 'USER');
INSERT INTO TAB_ROLE(ROL_USR_ID, ROL_NAME) VALUES (2, 'USER');